-- channel 테이블 (FK 제약 없음, BIGINT PK, 1-depth 확장 대비)
CREATE TABLE tb_admin.channel (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_channel_id   BIGINT NULL,                 -- 부모 채널(확장 대비), DB FK 미생성
  code                VARCHAR(100) NOT NULL,       -- 채널 코드
  name                VARCHAR(100) NOT NULL,       -- 채널명
  is_active           BOOLEAN NOT NULL DEFAULT FALSE, -- 사용여부 (기본: 비활성)
  contract_date       DATE NULL,                   -- 계약일자
  ratio               DECIMAL(15,6) NOT NULL DEFAULT 0, -- 비율 값(예: 0~1)
  sort_order          INTEGER NOT NULL DEFAULT 0,

  -- 감사/삭제 메타
  created_tz          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_tz          TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by          VARCHAR(100) NOT NULL DEFAULT '',
  updated_by          VARCHAR(100) NOT NULL DEFAULT '',
  is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_tz          TIMESTAMPTZ NULL,
  deleted_by          VARCHAR(100) NULL
);

-- 유니크 & 조회 인덱스
CREATE UNIQUE INDEX ux_channel_code_root
  ON tb_admin.channel (code)
  WHERE parent_channel_id IS NULL;  -- 루트만 전역 유니크

CREATE UNIQUE INDEX ux_channel_parent_code
  ON tb_admin.channel (parent_channel_id, code)
  WHERE parent_channel_id IS NOT NULL; -- 서브: 동일 부모 내 유니크

CREATE INDEX ix_channel_parent_sort
  ON tb_admin.channel (parent_channel_id, sort_order);

-- ------------------------------------------------------------------
-- 주석(Comment) 정의
-- ------------------------------------------------------------------
COMMENT ON TABLE tb_admin.channel IS
'채널/서브채널 관리 테이블. 현재는 1-depth만 사용하나 parent_channel_id로 확장 가능.
DB에는 FK 제약을 두지 않으며, 깊이/참조 일관성은 애플리케이션(EF Core) 레벨에서 검증.';

COMMENT ON COLUMN tb_admin.channel.id                IS 'PK (BIGINT, IDENTITY).';
COMMENT ON COLUMN tb_admin.channel.parent_channel_id IS '부모 채널 ID(루트는 NULL). FK 미생성. 현재 1-depth만 허용(부모는 반드시 루트).';
COMMENT ON COLUMN tb_admin.channel.code              IS '채널 코드. 루트: 전역 유니크 / 서브: (parent_channel_id, code) 유니크.';
COMMENT ON COLUMN tb_admin.channel.name              IS '채널명 (표시용).';
COMMENT ON COLUMN tb_admin.channel.is_active         IS '사용 여부. 기본값 FALSE(비활성)로 시작하여 검증 후 활성.';
COMMENT ON COLUMN tb_admin.channel.contract_date     IS '계약일자(YYYY-MM-DD).';
COMMENT ON COLUMN tb_admin.channel.ratio             IS '비율 값(DECIMAL(15,6)). 일반적으로 0~1 범위를 권장(앱에서 검증).';
COMMENT ON COLUMN tb_admin.channel.sort_order        IS '표시/정렬 우선순위(오름차순).';

COMMENT ON COLUMN tb_admin.channel.created_tz        IS '생성 시각(TIMESTAMPTZ).';
COMMENT ON COLUMN tb_admin.channel.updated_tz        IS '수정 시각(TIMESTAMPTZ). 업데이트 트리거/앱 로직으로 갱신 권장.';
COMMENT ON COLUMN tb_admin.channel.created_by        IS '생성자 식별자(계정/시스템).';
COMMENT ON COLUMN tb_admin.channel.updated_by        IS '수정자 식별자(계정/시스템).';
COMMENT ON COLUMN tb_admin.channel.is_deleted        IS '소프트 삭제 플래그.';
COMMENT ON COLUMN tb_admin.channel.deleted_tz        IS '소프트 삭제 시각(TIMESTAMPTZ).';
COMMENT ON COLUMN tb_admin.channel.deleted_by        IS '소프트 삭제 수행자.';

COMMENT ON INDEX tb_admin.ux_channel_code_root       IS '루트 채널(code) 전역 유니크(부분 인덱스: parent_channel_id IS NULL).';
COMMENT ON INDEX tb_admin.ux_channel_parent_code     IS '서브 채널의 (부모, code) 유니크(부분 인덱스: parent_channel_id IS NOT NULL).';
COMMENT ON INDEX tb_admin.ix_channel_parent_sort     IS '부모별 정렬/리스트 조회 최적화 인덱스.';

-- (선택) ratio 범위를 DB에서 강제하고 싶다면 주석 해제
-- ALTER TABLE channel ADD CONSTRAINT ck_channel_ratio_range
-- CHECK (ratio >= 0 AND ratio <= 1);

-- (선택) updated_tz 자동 갱신 트리거
-- CREATE OR REPLACE FUNCTION trg_set_updated_tz() RETURNS trigger AS $$
-- BEGIN
--   NEW.updated_tz := now();
--   RETURN NEW;
-- END; $$ LANGUAGE plpgsql;
-- CREATE TRIGGER set_updated_tz BEFORE UPDATE ON channel
-- FOR EACH ROW EXECUTE FUNCTION trg_set_updated_tz();
