-- =========================================================
-- SOCIAL_AUTH: SNS 로그인 자격(참조)
-- =========================================================
CREATE TABLE tb_admin.social_auth (
                                      id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      provider             VARCHAR(50) NOT NULL,              -- GOOGLE|KAKAO|NAVER|FACEBOOK|APPLE|...
                                      provider_user_id     VARCHAR(200) NOT NULL,             -- 외부 플랫폼 고유 ID
                                      provider_email       VARCHAR(500) NULL,                 -- 필요 시 Enc/Dec 저장
                                      provider_token       VARCHAR(2000) NULL,                -- 토큰/자격(민감, Enc/Dec 권장)

                                      created_tz           TIMESTAMPTZ NOT NULL DEFAULT now(),
                                      updated_tz           TIMESTAMPTZ NOT NULL DEFAULT now(),
                                      created_by           VARCHAR(100) NOT NULL DEFAULT '',
                                      updated_by           VARCHAR(100) NOT NULL DEFAULT '',
                                      is_deleted           BOOLEAN NOT NULL DEFAULT FALSE,
                                      deleted_tz           TIMESTAMPTZ NULL,
                                      deleted_by           VARCHAR(100) NULL
);

-- 인덱스/유니크
CREATE UNIQUE INDEX ux_social_auth_provider_uid_unique
    ON tb_admin.social_auth(provider, provider_user_id)
    WHERE is_deleted = FALSE;

-- 주석(테이블)
COMMENT ON TABLE tb_admin.social_auth IS 'SNS 로그인 자격. provider+provider_user_id는 소프트삭제 제외 전역 유일.';

-- 주석(컬럼)
COMMENT ON COLUMN tb_admin.social_auth.id               IS 'PK (BIGINT, IDENTITY).';
COMMENT ON COLUMN tb_admin.social_auth.provider         IS 'SNS 공급자 코드(GOOGLE/KAKAO/NAVER/FACEBOOK/APPLE 등).';
COMMENT ON COLUMN tb_admin.social_auth.provider_user_id IS '해당 공급자 내 사용자 고유 ID.';
COMMENT ON COLUMN tb_admin.social_auth.provider_email   IS '공급자 제공 이메일(옵션, Enc/Dec 가능).';
COMMENT ON COLUMN tb_admin.social_auth.provider_token   IS '공급자 토큰/자격 정보(민감, Enc/Dec 권장·만료 관리).';

COMMENT ON COLUMN tb_admin.social_auth.created_tz       IS '생성 시각.';
COMMENT ON COLUMN tb_admin.social_auth.updated_tz       IS '수정 시각.';
COMMENT ON COLUMN tb_admin.social_auth.created_by       IS '생성자 식별자.';
COMMENT ON COLUMN tb_admin.social_auth.updated_by       IS '수정자 식별자.';
COMMENT ON COLUMN tb_admin.social_auth.is_deleted       IS '소프트 삭제 플래그.';
COMMENT ON COLUMN tb_admin.social_auth.deleted_tz       IS '소프트 삭제 시각.';
COMMENT ON COLUMN tb_admin.social_auth.deleted_by       IS '소프트 삭제 수행자.';

-- 주석(인덱스)
COMMENT ON INDEX tb_admin.ux_social_auth_provider_uid_unique IS '동일 공급자 내 provider_user_id 중복 금지(소프트삭제 제외).';