-- =========================================================
-- USER: 단일 채널 소속 사용자
-- =========================================================
CREATE TABLE tb_admin."user" (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_id           BIGINT NOT NULL,
  email                VARCHAR(500) NOT NULL,               -- 앱에서 Enc/Dec
  password             VARCHAR(100) NULL,                   -- 비밀번호 해시(Argon2id/bcrypt 등)
  social_auth_idx      BIGINT NULL,                         -- social_auth.id 논리 연결(FK 미생성)

  family_name          VARCHAR(500) NOT NULL,               -- 성(Enc/Dec)
  given_name           VARCHAR(500) NOT NULL,               -- 이름(Enc/Dec)
  gender               VARCHAR(500) NULL,                   -- 성별(Enc/Dec)
  nickname             VARCHAR(500) NULL,                   -- 별명(Enc/Dec)
  phone_country_code   VARCHAR(500) NULL,                   -- 국가 코드(예 +82, Enc/Dec)
  phone_number         VARCHAR(500) NULL,                   -- 로컬 번호(Enc/Dec)
  nationality_code     VARCHAR(500) NULL,                   -- 국적(예 KR/US 등, Enc/Dec)

  point                DECIMAL(15,6) NOT NULL DEFAULT 0,    -- 포인트 잔액

  is_active            BOOLEAN NOT NULL DEFAULT TRUE,       -- 기본 활성
  email_verified_tz    TIMESTAMPTZ NULL,
  last_login_tz        TIMESTAMPTZ NULL,
  failed_login_count   INTEGER NOT NULL DEFAULT 0,
  locked_until_tz      TIMESTAMPTZ NULL,

  created_tz           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_tz           TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by           VARCHAR(100) NOT NULL DEFAULT '',
  updated_by           VARCHAR(100) NOT NULL DEFAULT '',
  is_deleted           BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_tz           TIMESTAMPTZ NULL,
  deleted_by           VARCHAR(100) NULL
);

-- 인덱스/유니크
CREATE UNIQUE INDEX ux_user_channel_email_unique
  ON tb_admin."user"(channel_id, email)
  WHERE is_deleted = FALSE;

CREATE UNIQUE INDEX ux_user_social_auth_idx_unique
  ON tb_admin."user"(social_auth_idx);

CREATE INDEX ix_user_channel_active
  ON tb_admin."user"(channel_id, is_active, created_tz DESC);

-- 주석(테이블)
COMMENT ON TABLE tb_admin."user" IS '단일 채널 소속 사용자. 이메일/이름/성별/닉네임/전화/국적은 앱(.NET)에서 암호화하여 저장/복호화.';

-- 주석(컬럼)
COMMENT ON COLUMN tb_admin."user".id                 IS 'PK (BIGINT, IDENTITY).';
COMMENT ON COLUMN tb_admin."user".channel_id         IS '소속 채널 ID. FK 미생성(앱에서 정합성 검증).';
COMMENT ON COLUMN tb_admin."user".email              IS '사용자 이메일(Enc/Dec 대상). 채널 단위 유일(소프트삭제 제외).';
COMMENT ON COLUMN tb_admin."user".password           IS '비밀번호 해시(Argon2id/bcrypt 등). 평문 저장 금지.';
COMMENT ON COLUMN tb_admin."user".social_auth_idx    IS '연결된 social_auth의 id 값(논리 연결, FK 없음). 1:1 가정.';

COMMENT ON COLUMN tb_admin."user".family_name        IS '여권식 성(Enc/Dec).';
COMMENT ON COLUMN tb_admin."user".given_name         IS '여권식 이름(Enc/Dec).';
COMMENT ON COLUMN tb_admin."user".gender             IS '성별(Enc/Dec). 코드/문자열 정책은 앱에 따름.';
COMMENT ON COLUMN tb_admin."user".nickname           IS '별명(Enc/Dec).';
COMMENT ON COLUMN tb_admin."user".phone_country_code IS '전화 국가 코드(예 +82, Enc/Dec).';
COMMENT ON COLUMN tb_admin."user".phone_number       IS '전화 로컬 번호(Enc/Dec).';
COMMENT ON COLUMN tb_admin."user".nationality_code   IS '국적 코드/값(Enc/Dec).';

COMMENT ON COLUMN tb_admin."user".point              IS '포인트 잔액(DECIMAL(15,6)). 음수 방지는 앱/비즈니스 규칙으로 관리.';

COMMENT ON COLUMN tb_admin."user".is_active          IS '계정 활성 여부. 기본 TRUE.';
COMMENT ON COLUMN tb_admin."user".email_verified_tz  IS '이메일 인증 시각(LOCAL 계정).';
COMMENT ON COLUMN tb_admin."user".last_login_tz      IS '마지막 로그인 시각.';
COMMENT ON COLUMN tb_admin."user".failed_login_count IS '로그인 실패 누적 횟수.';
COMMENT ON COLUMN tb_admin."user".locked_until_tz    IS '계정 잠금 해제 예정 시각.';

COMMENT ON COLUMN tb_admin."user".created_tz         IS '생성 시각.';
COMMENT ON COLUMN tb_admin."user".updated_tz         IS '수정 시각.';
COMMENT ON COLUMN tb_admin."user".created_by         IS '생성자 식별자.';
COMMENT ON COLUMN tb_admin."user".updated_by         IS '수정자 식별자.';
COMMENT ON COLUMN tb_admin."user".is_deleted         IS '소프트 삭제 플래그.';
COMMENT ON COLUMN tb_admin."user".deleted_tz         IS '소프트 삭제 시각.';
COMMENT ON COLUMN tb_admin."user".deleted_by         IS '소프트 삭제 수행자.';

-- 주석(인덱스)
COMMENT ON INDEX tb_admin.ux_user_channel_email_unique IS '같은 채널에서 이메일 중복 금지(소프트삭제 제외). 암호화 사용 시 결정적 암호화 또는 앱 레벨 중복 검사 필요.';
COMMENT ON INDEX tb_admin.ux_user_social_auth_idx_unique IS '사용자 ↔ social_auth 1:1 연결 가정(여러 NULL 허용).';
COMMENT ON INDEX tb_admin.ix_user_channel_active IS '채널·활성 상태·생성일 내림차순 조회 최적화.';
